name: ihealthy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

  percent_indicator: ^4.2.3
  # Banco de dados local
  sqflite: ^2.4.2
  path: ^1.9.1

  # Pacotes adicionais
  google_fonts: ^6.1.0
  provider: ^6.1.2
  flutter_local_notifications: ^17.2.2
  fl_chart: ^0.68.0
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
